name: Bug Report
description: Report an Issue or Bug
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        We're sorry to hear you have a problem. Can you help us solve it by providing the following details.

  - type: textarea
    id: what-happened
    attributes:
      label: What Happened
      description: What did you expect to happen?
      placeholder: |
        Describe the issue in detail.

        Expected:
        - ...

        Actual:
        - ...
    validations:
      required: true

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to Reproduce
      description: How did this occur? Please add any configuration values used and provide reliable reproduction steps.
      placeholder: |
        1. Install the package...
        2. Configure...
        3. Run...
        4. Observe the error...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our package are you running?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: php-version
    attributes:
      label: PHP Version
      description: What version of PHP are you running?
      placeholder: "8.3.10"
    validations:
      required: true

  - type: dropdown
    id: operating-systems
    attributes:
      label: Operating System
      description: On which operating systems does the problem occur?
      multiple: true
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true